{% set name = "textual-dev" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textual_dev-{{ version }}.tar.gz
  sha256: bf1a50eaaff4cd6a863535dd53f06dbbd62617c371604f66f56de3908220ccd5

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv
  entry_points:
    - textual = textual_dev.cli:run

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.2.0
    - pip
  run:
    - python >={{ python_min }},<4
    - textual >=0.86.2
    - textual-serve >=1.0.3
    - aiohttp >=3.8.1
    - click >=8.1.2
    - msgpack-python >=1.0.3
    - typing_extensions >=4.4.0,<5.0.0

test:
  requires:
    - python {{ python_min }}
  commands:
    - textual --help

about:
  home: https://github.com/Textualize/textual-dev
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Development tools for working with Textual
  dev_url: https://github.com/Textualize/textual-dev
  doc_url: https://textual.textualize.io/guide/devtools

extra:
  recipe-maintainers:
    - davidbrochart
